language: objective-c
cache:
  directories:
  - Lib/vendor
install:
- "(cd Lib && bundle install --path=vendor/bundle --binstubs=vendor/bin)"
before_script:
- ./Lib/Scripts/decode_cert.sh || true
- ./Lib/Scripts/add_key.sh || true
script:
- "(cd Lib && travis_retry bundle exec rake $ACTION)"
matrix:
  include:
  - osx_image: xcode11
    env: ACTION=build
  - osx_image: xcode11
    env: ACTION='build:carthage'
  - osx_image: xcode11
    env: ACTION='test:iphonesimulator'
  - osx_image: xcode11
    env: ACTION='test:appletvsimulator'
  - osx_image: xcode11
    env: ACTION='test:macosx'
  # Mac Catalyst requires macOS Catalina. But no CI service supports running tests on Catalina yet.
  # - osx_image: xcode11
  #   script: xcodebuild test -workspace KeychainAccess.xcworkspace -scheme KeychainAccess -configuration Debug -enableCodeCoverage YES -derivedDataPath build -hideShellScriptEnvironment -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst' -only-testing:KeychainAccessTests-MacCatalyst SWIFT_VERSION=5.1 GCC_SYMBOLS_PRIVATE_EXTERN=NO

  - osx_image: xcode10.3
    env: ACTION=build
  - osx_image: xcode10.3
    env: ACTION='build:carthage'
  - osx_image: xcode10.3
    env: ACTION='test:iphonesimulator'
  - osx_image: xcode10.3
    env: ACTION='test:appletvsimulator'
  - osx_image: xcode10.3
    env: ACTION='test:macosx'

  - osx_image: xcode10.2
    env: ACTION=build
  - osx_image: xcode10.2
    env: ACTION='build:carthage'
  - osx_image: xcode10.2
    env: ACTION='test:iphonesimulator'
  - osx_image: xcode10.2
    env: ACTION='test:appletvsimulator'
  - osx_image: xcode10.2
    env: ACTION='test:macosx'

  - osx_image: xcode10
    env: ACTION=build
  - osx_image: xcode10
    env: ACTION='build:carthage'
  - osx_image: xcode10
    env: ACTION='test:iphonesimulator'
  - osx_image: xcode10
    env: ACTION='test:appletvsimulator'
  - osx_image: xcode10
    env: ACTION='test:macosx'

  - osx_image: xcode9.4
    env: ACTION=build
  - osx_image: xcode9.4
    env: ACTION='build:carthage'
  - osx_image: xcode9.4
    env: ACTION='test:iphonesimulator'
  - osx_image: xcode9.4
    env: ACTION='test:appletvsimulator'
  - osx_image: xcode9.4
    env: ACTION='test:macosx'
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - secure: KL59HA2XSRa215qVXXnFpx48Tb/k+vNfFAbzyc+0M4mXl1VhSJv3bkTslqDrX822t3iFDFYhXbJ6aUo7szSdcbnCXU7VIhNPRK5QM00eS1AI4V0UwDQZ06g2f4Dmt+cQxACg+0CB0OaPnUCA4rkQQKeBMAWa67Tp2hNgQHwsnio=
  - secure: B8zXiyX1zEq6uWaCxap5iW1joQBoOjNjSUlcs1t+QKdaFCFtjOI8C1JCClzk7rTnGNDDrhahFlE8yskSNKoBsaW2UJ8TzPIkD4F2pkxTHkaFQl/GBsdbHdOUFL4h0/zGQ6wY1Qhw7C+8+3U+1c9QbnNw6jOQwXTF6gs/XTNzG9Y=
branches:
  only:
  - master
